// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleGastosAPI.Migrations
{
    [DbContext(typeof(ConnectionContext))]
    partial class ConnectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleGastosAPI.Domain.Models.Categoria", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("finalidade")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("ControleGastosAPI.Domain.Models.Pessoa", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("idade")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("id");

                    b.ToTable("pessoas");
                });

            modelBuilder.Entity("ControleGastosAPI.Domain.Models.Transacao", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("categoriaid")
                        .HasColumnType("uuid");

                    b.Property<string>("descricao")
                        .HasColumnType("text");

                    b.Property<Guid>("pessoaid")
                        .HasColumnType("uuid");

                    b.Property<int>("tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("valor")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("pessoaid");

                    b.ToTable("transacoes");
                });

            modelBuilder.Entity("ControleGastosAPI.Domain.Models.Transacao", b =>
                {
                    b.HasOne("ControleGastosAPI.Domain.Models.Pessoa", null)
                        .WithMany("transacoes")
                        .HasForeignKey("pessoaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleGastosAPI.Domain.Models.Pessoa", b =>
                {
                    b.Navigation("transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
